---
# handlers file for ha-test
- name: reload haproxy
  systemd:
    name: haproxy.service
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  ignore_errors: yes

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
  tags: runkeep