---
- hosts: k8s
  handlers:
    - name: rs etcd
      systemd:
        name: etcd.service
        state: restarted

  tasks:
    - name: 拷贝etcd文件
      copy:
        mode: +x
        src: ./{{ item }}
        dest: /usr/local/bin
      loop:
        - etcd
        - etcdctl

    - name: 创建etcd配置文件
      template:
        src: ./etcd.config.yml.j2
        dest: /etc/etcd/etcd.config.yml

    - name: 创建etcd证书目录
      file:
        path: /etc/kubernetes/pki/etcd
        state: present

    - name: 连接etcd证书目录
      shell:
        cmd: "ln -s /etc/etcd/ssl/* /etc/kubernetes/pki/etcd/"

    - name: 创建etcd守护进程服务
      template:
        src: ./etcd.service.j2
        dest: usr/lib/systemd/system/etcd.service
      notify: rs etcd
