---
- hosts: k8s
  gather_facts: false
  vars_files: ./var.yml
  tasks:
    - name: 安装libselinux-python3
      yum:
        name: "libselinux-python3"
        state: present

    - name: 编辑hosts文件
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{ hosts }}"
    # - name: 编辑hosts文件
    #   template:
    #     src: ./hosts.j2
    #     dest: /etc/hosts
    #     backup: yes

    # - name: 收集hosts文件
    #   shell: "cat /etc/hosts"
    #   register: hosts

    # - name: 展示hosts文件
    #   debug:
    #     msg: "{{ hosts }}"

    # - name: 收集etc目录
    #   shell: "ll /etc/ | grep 'hosts'"
    #   register: lletc

    # - name: 展示etc目录
    #   debug:
    #     msg: "{{ lletc }}"
