---
- hosts: master
  remote_user: root
  tasks:
    - name: rs haproxy
      systemd:
        daemon_reload: yes
        name: haproxy
        enabled: true
        state: restarted

    - name: rs keepalived
      systemd:
        daemon_reload: yes
        name: keepalived
        enabled: true
        state: restarted
