---
# 引入自定义变量文件
- vars_files: ./var.yml
# 安装基础软件、进行基础设置、安装containerd作为Runtime
- hosts: k8s
  remote_user: root
  roles:
    - dnf
    - init
    - containerd
  tags: o

# 生成集群证书
- hosts:
    - master
  remote_user: root
  roles:
    - pki
  tags: pki

# 安装etcd集群
- hosts:
    - etcd
  remote_user: root
  roles:
    - etcd
  tags: etcd

# 安装kube-apiserver高可用（haproxy、keepalived）
- hosts:
    - master
  remote_user: root
  roles:
    - lb
    # 安装master节点
    - master
    # 设置RBAC控制
    - bootstrap

# 安装node节点
- hosts:
    - k8s
  remote_user: root
  roles:
    - node
  tags: node

# 安装cilium网络插件
- hosts:
    - 192.168.12.31
  roles:
    - cilium
    # 安装coreDNS插件
    - coredns
  tags: cilium

# 安装Metrics Server

