---
- hosts: k8s
  remote_user: root
  roles:
    # - dnf
    # - init
    # - containerd

- hosts: master
  remote_user: root
    - pki

- hosts: etcd
  remote_user: root
  roles:
    - etcd

- hosts: master
  remote_user: root
  roles:
    - lb

- hosts: 192.168.12.31
  remote_user: root
  roles:
    - bootstrap
