---
- hosts: k8s
  remote_user: root
  roles:
    - dnf
    - init
    - containerd
  tags: o

- hosts: k8s
  gather_facts: false
  vars_files: ./var.yml
  tasks:
    - name: 安装libselinux-python3
      yum:
        name: "libselinux-python3"
        state: present

    - name: 编辑hosts文件
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{ hosts }}"

- hosts: master
  tasks:
    - name: 拷贝kubernetes安装文件
      copy:
        src: ./k8s_server/{{ item }}
        dest: /usr/local/bin
        mode: +x
      loop:
        - kube-apiserver
        - kube-controller-manager
        - kubectl
        - kubelet
        - kube-proxy
        - kube-scheduler
  tags: kube

- hosts: 192.168.12.31
  tasks:
    - name: k8s-master01配置免密
      script:
        cmd: "./ssh/ssh.sh"

- hosts:
    - master
  remote_user: root
  roles:
    - pki
  tags: pki

- hosts:
    - etcd
  remote_user: root
  roles:
    - etcd
  tags: etcd

- hosts:
    - master
  remote_user: root
  roles:
    - lb
  tags: lb

- hosts:
    - master
  remote_user: root
  roles:
    - master
  tags: m

- hosts:
    - master
  remote_user: root
  roles:
    - bootstrap
  tags: boot

- hosts:
    - k8s
  remote_user: root
  vars:
    m1: 192.168.12.31
  roles:
    - node
  tags: node
