---
# 引入自定义变量文件
- vars_files: ./var.yml

# 安装基础软件
# 进行基础设置
# 安装containerd作为Runtime
- hosts: k8s
  remote_user: root
  roles:
    - dnf
    - init
    - containerd
  tags: o

# 生成集群证书
- hosts:
    - master
  remote_user: root
  roles:
    - pki
  tags: pki

# 安装etcd集群
- hosts:
    - etcd
  remote_user: root
  roles:
    - etcd
  tags: etcd

# 安装kube-apiserver高可用（haproxy、keepalived）
# 安装master节点
# 设置RBAC控制
- hosts:
    - master
  remote_user: root
  roles:
    - lb
    - master
    - bootstrap

# 安装node节点
- hosts:
    - k8s
  remote_user: root
  roles:
    - node
  tags: node

# 部署cilium网络插件
# 部署coreDNS插件
- hosts:
    - { m1 }
  roles:
    - cilium
    - coredns
  tags: cilium

# 部署kubernetes应用（Metrics Server dashboard ingress）
- hosts:
    - { m1 }
  roles:
    - app

# 部署测试项目
- hosts:
    - { m1 }
  roles:
    - test
