---
- hosts: k8s
  remote_user: root
  roles:
    - dnf
    # - init
    # - containerd

# - hosts:
#     - master
#   remote_user: root
#     - pki

- hosts:
    - etcd
  remote_user: root
  roles:
    - etcd

- hosts:
    - master
  remote_user: root
  roles:
    - lb
  tags: lb

- hosts:
    - master
  remote_user: root
  roles:
    - master
  tags: m

- hosts:
    - master
  remote_user: root
  roles:
    - bootstrap
  tags: boot
