---
- hosts: k8s
  tasks:
    - name: 设置主机名称
      shell: "hostnamectl set-hostname {{ hostname | quote }}"
      # shell: "hostnamectl set-hostname {{ item | quote }}"
      # shell: "hostnamectl set-hostname 333"
      # loop:
      #   - master001
      #   - master002
      #   - node001

    - name: 收集与展示主机名称
      block:
        - name: 收集主机名称
          shell: "hostname"
          register: showhostname

        - name: 展示主机名
          debug:
            # msg: '{{ ansible_hostname }}'
            msg: "{{ showhostname.stdout }}"

    - name: fact收集的主机名
      debug:
        msg: "fact收集的主机名{{ ansible_hostname }}"
