---
- hosts: ll
  tasks:
    # - name: 测试fact变量
    #   debug:
    #     msg: "{{ ansible_distribution }}"
    - name:
      shell:
        cmd: "crictl --version"
      register: get_node

    - name:
      debug:
        msg: "{{ get_node['stdout'] }}"
