---
# tasks file for app
- name: 部署Metrics Server
  block:
    - name: 拷贝components.yaml
      copy:
        src: components.yaml
        dest: /root/components.yaml

    - name: 部署Metrics-server
      shell:
        cmd: "kubectl apply -f components.yaml"
        chdir: "/root"

- name: 部署dashboard
  block:
    - name: 判断dashboard 包是否存在
      ignore_errors: yes
      stat:
        path: /root/kubernetes-dashboard/values.yaml
      register: dashboard

    - name: 拷贝helm的dashboard chart
      copy:
        src: ../../package/kubernetes-dashboard
        dest: /root
      when: "dashboard.stat.isreg is not defined"

    - name: 使用helm安装dashboard
      shell:
        cmd: "helm install kubernetes-dashboard ./kubernetes-dashboard --namespace kube-system"
        chdir: "/root"

    - name: 创建dashboard管理员token
      block:
        - name: 拷贝dashboard-user.yaml服务账户文件
          copy:
            src: dashboard-user.yaml
            dest: /root

        - name: 应用dashboard-user.yaml
          shell:
            cmd: "kubectl  apply -f dashboard-user.yaml"

# - name: 部署ingress
#   block:
#     - name: 拷贝ingress
#       copy:
#         src: "{{ item }}"
#         dest: /root/ingress/
#       loop:
#         - deploy.yaml
#         - backend.yaml
#         - ingress-demo-app.yaml

#     - name: 应用ingress
#       shell:
#         cmd: "kubectl  apply -f deploy.yaml && kubectl  apply -f backend.yaml &&kubectl  apply -f ingress-demo-app.yaml "
#         chdir: /root/ingress/
