---
# tasks file for app
- name: 部署Metrics Server
  block:
    - name: 拷贝components.yaml
      copy:
        src: components.yaml
        dest: /root/components.yaml

    - name: 部署Metrics-server
      shell:
        cmd: "kubectl replace --force -f components.yaml"
        chdir: "/root"

- name: 部署dashboard
  block:
    # - name: 判断dashboard 包是否存在
    #   ignore_errors: yes
    #   stat:
    #     path: /root/kubernetes-dashboard-7.1.1.tgz
    #   register: dashboard

    - name: 拷贝helm的dashboard chart
      copy:
        src: ../../package/dashboard/kubernetes-dashboard-7.1.1.tgz
        dest: /root
      # when: "dashboard.stat.isreg is not defined"

    - name: 使用helm安装dashboard
      shell:
        cmd: "helm install kubernetes-dashboard ./kubernetes-dashboard-7.1.1.tgz --namespace kube-system"
        chdir: "/root"

    - name: 创建dashboard管理员token
      block:
        - name: 拷贝dashboard-user.yaml服务账户文件
          copy:
            src: dashboard-user.yaml
            dest: /root

        - name: 应用dashboard-user.yaml
          shell:
            cmd: "kubectl replace --force -f dashboard-user.yaml"

- name: 部署nfs-storage
  block:
    - name: 拷贝nfs-storage.yaml文件
      template:
        src: nfs-storage.yaml.j2
        dest: /root/nfs-storage.yaml

    - name: 应用nfs-storageyaml
      shell:
        cmd: "kubectl replace --force -f ./nfs-storage.yaml"
        chdir: "/root"

- name: 使用Helm部署EFK
  block:
    - name: 拷贝EFK相关组件
      copy:
        src: "../../package/efk/{{ item }}"
        dest: "/root"
      loop:
        - elasticsearch-8.5.1.tgz 
        - filebeat-8.5.1.tgz
        - kibana-8.5.1.tgz
        - metricbeat-8.5.1.tgz

    - name: 创建logs命名空间
      k8s:
        name: logs
        api_version: v1
        kind: Namespace
        state: present
      # shell:
      #   cmd: "kubectl create namespace logs"

    - name: 使用helm部署EFK相关组件
      shell:
        cmd: "helm install {{ item.1 }} ./{{ item.0 }} --namespace logs"
        chdir: "/root"
      # helm:
      #   name: "{{ item }}"
      #   atomic: true
      #   chart_ref: "/root/{{ item }}"
      #   create_namespace: true
      #   release_namespace: logs
      with_together:
        - [ elasticsearch-8.5.1.tgz, filebeat-8.5.1.tgz, metricbeat-8.5.1.tgz, kibana-8.5.1.tgz ]
        - [ elasticsearch, filebeat, metricbeat, kibana ]



# - name: 部署ingress
#   block:
#     - name: 拷贝ingress
#       copy:
#         src: "{{ item }}"
#         dest: /root/ingress/
#       loop:
#         - deploy.yaml
#         - backend.yaml
#         - ingress-demo-app.yaml

#     - name: 应用ingress
#       shell:
#         cmd: "kubectl  apply -f deploy.yaml && kubectl  apply -f backend.yaml &&kubectl  apply -f ingress-demo-app.yaml "
#         chdir: /root/ingress/
