---
# tasks file for coredns
- name: 安装CoreDNS插件
  block:
    # - name: 添加coredns源
    #   shell:
    #     cmd: "helm repo add coredns https://coredns.github.io/helm"

    # - name: 拉取coredns仓库
    #   shell:
    #     cmd: "helm pull coredns/coredns"
    #     chdir: /root

    # - name: 解压coredns
    #   unarchive:
    #     src: /root/coredns-*.tgz
    #     dest: /root
    #     remote_src: yse

    - name: 判断包是否存在
      ignore_errors: yes
      stat:
        path: /root/coredns-1.29.0.tgz
      register: coredns

    - name: 拷贝CoreDNS helm包
      copy:
        src: ../../package/coredns/coredns-1.29.0.tgz
        dest: /root
      when: "coredns.stat.isreg is not defined"

    - name: 安装coredns
      shell:
        cmd: "helm install  coredns ./coredns-1.29.0.tgz -n kube-system"
        chdir: "/root"
