---
# handlers file for node
- name: rs kubelet
  systemd:
    name: kubelet.service
    state: restarted
    enabled: true
    daemon_reload: yes

- name: rs kube-proxy
  systemd:
    name: kube-proxy.service
    state: restarted
    enabled: true
    daemon_reload: yes
