---
# handlers file for init
- name: rs NM
  systemd:
    state: restarted
    name: NetworkManager

- name: rs chrony
  systemd:
    state: restarted
    name: chronyd
    enabled: true

- name: rs systemd-modules-load
  systemd:
    state: restarted
    name: systemd-modules-load.service
    enabled: true

- name: rs sysctl
  shell:
    cmd: sysctl --system