---
# handlers file for master
- name: rs apiserver
  systemd:
    daemon_reload: yes
    name: kube-apiserver
    enabled: true
    state: restarted

- name: rs manager
  systemd:
    daemon_reload: yes
    name: kube-controller-manager
    enabled: true
    state: restarted

- name: rs scheduler
  systemd:
    daemon_reload: yes
    name: kube-scheduler
    enabled: true
    state: restarted
