---
# tasks file for etcd
- name: 拷贝etcd文件
  copy:
    mode: +x
    src: ../../package/{{ item }}
    dest: /usr/local/bin
  loop:
    - etcd
    - etcdctl

- name: 创建etcd配置文件
  template:
    src: etcd.config.yml.j2
    dest: /etc/etcd/etcd.config.yml
  tags: ts

# - name: 创建etcd证书目录
#   file:
#     path: /etc/kubernetes/pki/etcd
#     state: directory
#   tags: ts

- name: 连接etcd证书目录
  # shell:
  #   cmd: "ln -s /etc/etcd/ssl/* /etc/kubernetes/pki/etcd/"
  # ignore_errors: yes
  tags: ts
  ignore_errors: yes
  file:
    state: link
    src: /etc/etcd/ssl
    dest: /etc/kubernetes/pki/etcd
    force: yes

- name: 创建etcd守护进程服务
  copy:
    src: etcd.service
    dest: /usr/lib/systemd/system/etcd.service
  # changed_when: yes
  notify: rs etcd
  tags: ts

- meta: flush_handlers

# - name: 检查etcd守护进程
#   block:
#     - name: 收集etcd守护进程信息
#       ignore_errors: yes
#       shell:
#         cmd: "systemctl status etcd | grep running "
#       register: etcd

#     - name: 启动etcd守护进程
#       systemd:
#         name: etcd
#         state: restarted
#         enabled: true
#         daemon_reload: yes
#       when: etcd.stdout == ""
