---
# tasks file for cilium
- name: 拷贝helm二进制文件
  copy:
    src: helm
    dest: /usr/local/bin/

- name: 添加cilium源
  shell:
    cmd: "helm repo add cilium https://helm.cilium.io"

- name: 拉取cilium仓库
  shell:
    cmd: "helm pull cilium/cilium"
    chdir: "/root"

- name: 解压cilium文件
  unarchive:
    src: "/root/cilium-*.tgz"
    dest: "/root"
    remote_src: yes

- name: 安装cilium
  shell:
    cmd: "helm install cilium cilium/cilium --namespace kube-system --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set prometheus.enabled=true --set operator.prometheus.enabled=true --set hubble.enabled=true --set hubble.metrics.enabled='{dns,drop,tcp,flow,port-distribution,icmp,http}' "
    chdir: "/root/cilium/"

- name: 拷贝monitoring-example.yaml
  copy:
    src: monitoring-example.yaml
    dest: "/root"

- name: 安装监控
  shell:
    cmd: "kubectl  apply -f monitoring-example.yaml"
    chdir: "/root"

