---
# tasks file for calico
- name:
  block:
    - name: 安装calico网络插件
      template:
        src: calico-typha.yaml.j2
        dest: /root/calico.yaml
    - name:
      shell:
        chdir: "/root/"
        cmd: "kubectl replace --force -f calico.yaml"
  when: ansible_default_ipv4['address'] == m1
