---
# tasks file for init
- name: 设置主机名称 .1
  hostname:
    name: "{{ hostname | quote }}"

- name: 关闭防火墙 .2
  block:
    - name: CentOS与openEuler关闭防火墙并禁止自启动 .2.1
      systemd:
        name: firewalld
        state: stopped
        enabled: false
      when: ansible_distribution == "openEuler"
      # tags: ts

- name: 关闭SELinux .3
  block:
    - name: CentOS与openEuler关闭SELinux
      selinux:
        state: disabled
      when: ansible_distribution == "openEuler"

- name: 关闭交换分区 .4
  block:
    - name: 注释fstab中的交换分区配置 .4.1
      replace:
        path: /etc/fstab
        regexp: "^(.*swap.*)$"
        replace: '# \1'
        backup: yes

    - name: 关闭交换分区并禁用系统的交换分区策略
      shell:
        cmd: "swapoff -a && sysctl -w vm.swappiness=0"

- name: CentOS与openEuler网络配置 .5
  block:
    - name: CentOS与openEuler取消NetworkManager对于cali*和tunl*的管理
      template:
        src: calico.conf.j2
        dest: /etc/NetworkManager/conf.d/calico.conf
        backup: yes
      notify: rs NM
  when: ansible_distribution == "openEuler"

- name: 时间同步 .6
  block:
    - name: 拷贝chrony服务端配置文件 .6.1
      template:
        src: chrony-service.conf.j2
        dest: /etc/chrony.conf
        backup: yes
      changed_when: yes
      notify: rs chrony
      when: ansible_default_ipv4['address'] == m1

    - name: 拷贝chrony客户端配置文件 .6.2
      template:
        src: chrony-client.conf.j2
        dest: /etc/chrony.conf
        backup: yes
      changed_when: yes
      notify: rs chrony
      when: ansible_default_ipv4['address'] != m1

- name: 配置ulimit .7
  block:
    - name: 修改最大文件数 .7.1
      shell:
        cmd: "ulimit -SHn 65535"

    - name: 拷贝limits.conf文件 .7.2
      template:
        src: limits.conf.j2
        dest: /etc/security/limits.conf
        backup: yes

- name: 配置hosts解析
  block:
    - name: 判断hosts解析是否添加
      shell:
        cmd: "cat /etc/hosts | grep k8s-master01"
      ignore_errors: yes
      register: cat_hosts

    - name: 编辑hosts文件
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{ hosts_list }}"
      when: cat_hosts.stdout == ""
  tags: hs

- name: k8s-master01配置免密
  ignore_errors: yes
  script:
    cmd: "ssh.sh"
  tags: sh
  when: ansible_default_ipv4['address'] == m1

- name: 拷贝kubernetes master安装文件
  copy:
    src: ../../package/{{ item }}
    dest: /usr/local/bin
    mode: +x
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kubectl
    - kubelet
    - kube-proxy
    - kube-scheduler
  when: ansible_default_ipv4['address'] is subset(master)

- name: 拷贝kubernetes node安装文件
  copy:
    src: ../../package/{{ item }}
    dest: /usr/local/bin
    mode: +x
  loop:
    - kubelet
    - kube-proxy
  when: ansible_default_ipv4['address'] is subset(node)
